umbella/views.py
# import flask module from the Flask package 
from flask import Flask
from flask import Blueprint
from flask import render_template
from flask import url_for
from flask import request
from flask import session
from flask import flash
from flask import redirect

# import models
from .models import Series
from .models import Umbrella
from .models import Order

# import dateTime module
from datetime import datetime
from .forms import CheckoutForm
from . import db

# main back-end code
bp = Blueprint('main', __name__)

# setting the route in index page
# sending series as data
@bp.route('/') # veiw function
def index():
    series = Series.query.order_by(Series.id).all()
    overall = Umbrella.query.order_by(Umbrella.name).all()
    return render_template('index.html', series=series, overall=overall)

# direct to privacy page
@bp.route('/privacyterms')  # veiw function
def privacy():
    series = Series.query.order_by(Series.id).all()
    return render_template('privacy.html', series=series)

# direct to brand story page
@bp.route('/story')  # veiw function
def story():
    
    series = Series.query.order_by(Series.id).all()
    return render_template('story.html', series=series)

# direct to search result page
@bp.route('/search/')
def search():
    search = request.args.get('search')
    print(search)
    search = '%{}%'.format(search)
    overall = Umbrella.query.filter(Umbrella.description.like(
        search)+Umbrella.name.like(search)+Umbrella.artist.like(search)+Umbrella.description_1.like(search)+Umbrella.description_2.like(search)).all()
    if overall == []:
        flash('We are sorry, there is no relative result for the keyword...')
    series = Series.query.order_by(Series.id).all()
    return render_template('search.html', Umbrellas=overall, series=series)


# setting the route in umbrella pages
@bp.route('/series/<int:seriesid>/')  
def seriesUmbrellas(seriesid):
    seriesUmbrellas = Umbrella.query.filter(Umbrella.series_id == seriesid)
    selectedItem = Series.query.filter(Series.id == seriesid).first()
    series = Series.query.order_by(Series.name).all()
    return render_template('series.html', umbrellas=seriesUmbrellas, item=selectedItem, series=series)

# setting the route in umbrella pages
@bp.route('/umbrella/<int:umbrellaid>/')
def Umbrellas(umbrellaid):
    selectedUmbrellas = Umbrella.query.filter(Umbrella.id == umbrellaid).first()
    selectedItem = Series.query.filter(
        Series.id == selectedUmbrellas.series_id).first()
    series = Series.query.order_by(Series.name).all()
    return render_template('umbrella.html', umbrella=selectedUmbrellas, item=selectedItem, series=series)


# setting the route in oder page
@bp.route('/order', methods=['POST', 'GET'])
def order():
    umbrella_id = request.values.get('umbrella_id')

    # check if it is a new order
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None
    
     # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', surname='', title='', email='',
                      postCode='', address='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for umbrella in order.umbrellas:
            totalprice = totalprice + umbrella.price

    # are we adding an item?
    if umbrella_id is not None and order is not None:
        umbrella = Umbrella.query.get(umbrella_id)
        if umbrella not in order.umbrellas:
            try:
                order.umbrellas.append(umbrella)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your cart'
            return redirect(url_for('main.order'))
        else:
            flash('item already in cart')
            return redirect(url_for('main.order'))
    
    series = Series.query.order_by(Series.name).all()

    return render_template('order.html', order=order, totalprice=totalprice, series=series)



# setting when user want to delete an order
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))


# setting when user want to delete a specific item 
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        umbrella_to_delete = Umbrella.query.get(id)
        try:
            order.umbrellas.remove(umbrella_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# direct to checkout page
@bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    form = CheckoutForm()
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.title = form.title.data
            order.postCode = form.postcode.data
            order.address = form.address.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for umbrella in order.umbrellas:
                totalcost = totalcost + umbrella.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash(
                    'Thank you for choosing Umbella! successfully submit your order.')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'

        series = Series.query.order_by(Series.name).all()
        return render_template('checkout.html', form=form, series=series)

umbella/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- basic information -->
    <link
      rel="shortcut icon"
      href="{{url_for('static', filename='img/Umbella_shorticon.jpg')}}"
    />
    <title>the Umbella</title>
    <meta
      name="description"
      content="Everyone deserves a special umbrella that can tell a story for themselves. The Umbella is an online umbrella eCommerce store that sells one high-quality umbrella with multiple amazing cover designs. The Umbella dedicates to provide plenty of shade pattern option which can be categorised in different series."
    />
    <meta
      name="keywords"
      content="umbella, artist umbrella, pattern umbrella, design umbrella"
    />
    <meta name="author" content="Charles Swei, n10669710@qut.edu.au" />
    <meta name="copyright" content="the Umbella Copyright 2020" />
    <meta property="og:title" content="Umbella" />
    <meta property="og:type" content="umbrella ecommerce store" />

    <!-- for multiple broweser compatibility -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- Google font implement -->
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;800&display=swap"
      rel="stylesheet"
    />

    <!-- the umbella customized stylesheet -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/theUmbella_style.css')}}"
    />

    <!-- scroll style  -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />

    <style>
      .flash_card {
        text-decoration: none !important;
      }
      .alert:hover {
        text-decoration: none !important;
        user-select: none;
        letter-spacing: 1px !important;
        transition: all 0.5s;
        transition-timing-function: ease;
      }
    </style>
  </head>

  <body>
    <header>
      <!--navbar creates a navigation bar -->
      <nav class="navbar navbar-expand-lg navbar-light sticky-top">
        <div class="container">
          <!-- Logo -->
          <a
            href="{{url_for('main.index')}}"
            class="navbar-brand"
            data-aos="fade-right"
            data-aos-delay="400"
          >
            <img
              src="{{url_for('static', filename='img/logo.svg')}}"
              alt="Umbella Logo"
              width="32"
              height="32"
            />
            <span>the Umbella</span>
          </a>
          <!-- a short description for the website -->
          <div
            class="collapse navbar-collapse describe"
            data-aos="fade-right"
            data-aos-delay="600"
          >
            A stylish online umbrella store
          </div>

          <!-- create a button for collapsing the menu -->
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggler"
            aria-controls="navbarToggler"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span
              ><img
                src="{{url_for('static', filename='img/symbols.svg')}}"
                alt="toggle"
                width="24"
                height="24"
            /></span>
          </button>

          <!-- Navbar -->
          <div class="collapse navbar-collapse" id="navbarToggler">
            <div class="navbar-nav ml-auto">
              <!-- individual menu item-->
              <a
                class="nav-item text-nav nav-link"
                href="{{url_for('main.index')}}"
                >Home</a
              >

              <!-- individual menu item-->
              <a
                class="nav-item text-nav nav-link"
                href="{{url_for('main.story')}}"
                >Portrait</a
              >

              <!-- individual menu item-->
              <div class="dropdown">
                <a
                  class="nav-item text-nav nav-link dropdown-toggle"
                  data-toggle="dropdown"
                  id="bookDropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  href="#"
                  >Style Series</a
                >
                <!-- dropdown menu item list -->
                <div class="dropdown-menu" aria-labelledby="bookDropdown">
                  {% for item in series%}
                  <a
                    class="dropdown-item"
                    href="{{ url_for('main.seriesUmbrellas', seriesid=item.id)}}"
                    >{{ item.name }}</a
                  >
                  <div class="dropdown-divider"></div>
                  {% endfor %}
                </div>
              </div>

              <!-- individual menu item-->
              <a
                class="nav-item text-nav nav-link"
                href="{{url_for('main.order')}}"
                >Cart</a
              >

              <!-- search box -->
              <form
                class="form-inline ml-xl-5 ml-lg-3 my-lg-0 form-row"
                action="{{url_for('main.search')}}"
              >
                <input
                  class="form-control mr-sm-2 form-control-sm col-7"
                  type="search"
                  placeholder="Looking for..."
                  name="search"
                />
                <button
                  class="btn btn-outline-light my-1 my-sm-0 btn-sm col-4"
                  type="submit"
                >
                  Search
                </button>
              </form>
            </div>
          </div>
        </div>
      </nav>

      {% with messages = get_flashed_messages() %} {% if messages %}
      <a class="flash_card" href="{{url_for('main.index')}}">
        <div
          class="alert font-weight-normal text-center m-3"
          role="alert"
          style="color: #e34249 !important; font-size: 1.2rem !important"
        >
          {% for message in messages %} {{ message }} {% endfor %}
        </div>
      </a>
      {% endif %} {% endwith %} {% block head %}{% endblock %}
    </header>

    <!-- main page content goes in container -->
    <div>
      <main class="text-center">{% block main %}{% endblock %}</main>
    </div>

    <footer
      class="container-fluid footer"
      data-aos="fade-up"
      data-aos-delay="100"
    >
      <div class="container py-5">
        <div class="row">
          <div class="col-12 col-md">
            <a href="{{url_for('main.index')}}" class="navbar-brand"
              ><img
                src="{{url_for('static', filename='img/Umbella_logo.jpg')}}"
                alt="Umbella Logo"
                width="32"
                height="32"
            /></a>

            <small class="d-block mb-3 text-secondary">© theUmbella 2020</small>
          </div>
          <div class="col-6 col-md">
            <h5>Style Series</h5>
            <ul class="list-unstyled text-small">
              {% for item in series%}
              <li>
                <a
                  class="text-secondary"
                  href="{{ url_for('main.seriesUmbrellas', seriesid=item.id)}}"
                  >{{ item.name }}</a
                >
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Portrait</h5>
            <ul class="list-unstyled text-small">
              <li>
                <a class="text-secondary" href="{{url_for('main.story')}}"
                  >the Umbella</a
                >
              </li>
              <li>
                <a
                  class="text-secondary"
                  target="blank"
                  href="https://goo.gl/maps/i6cMz1xaAnk7Duir9"
                  >Locations</a
                >
              </li>
              <li>
                <a class="text-secondary" href="{{ url_for('main.privacy')}}"
                  >Privacy</a
                >
              </li>
              <!-- <li><a class="text-secondary" href="#">Terms</a></li> -->
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Music</h5>
            <ul class="list-unstyled text-small">
              <li>
                <audio controls autoplay>
                  <source
                    src="{{url_for('static', filename='sound/Avenged_Sevenfold_ Dear_God.m4a')}}"
                    type="audio/ogg"
                  />
                  <source
                    src="{{url_for('static', filename='sound/Avenged_Sevenfold_ Dear_God.m4a')}}"
                  />
                  Your browser does not support the audio element.
                </audio>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <!-- customised JS -->
    <script src="{{url_for('static', filename='js/theUmbella_product.js')}}"></script>

    <!-- scrolling style -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

umbella/templates/index.html
{% extends 'base.html' %} {% block head %}
<!-- add a big banner to welcome user -->

<!-- Topic image -->
<div id="topic-story" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#topic-story" data-slide-to="0" class="active"></li>
    <li data-target="#topic-story" data-slide-to="1"></li>
    <li data-target="#topic-story" data-slide-to="2"></li>
    <li data-target="#topic-story" data-slide-to="3"></li>
    <li data-target="#topic-story" data-slide-to="4"></li>
    <li data-target="#topic-story" data-slide-to="5"></li>
  </ul>

  <!-- carousel banner conten -->
  <div class="carousel-inner">
    <div class="carousel-item active" style="max-height: 700px">
      <video
        class="d-block w-100"
        autoplay
        muted
        loop
        poster="{{url_for('static', filename='img/StorySlides_4.jpg')}}"
      >
        <source
          src="{{url_for('static', filename='img/WalingRain_1.mp4')}}"
          type="video/mp4"
        />
      </video>
      <div class="carousel-caption d-lg-block">
        <h1 class="display-4" data-aos="fade-up" data-aos-delay="100">
          A shower of new styles.
        </h1>
        <p class="lead" data-aos="fade-up" data-aos-delay="150">
          redefine yourslef with the umbella
        </p>
        <p
          class="text-small text-muted d-xl-block"
          data-aos="fade-up"
          data-aos-delay="200"
        >
          Umbrella cant stop rain but make us to stand in rain. Confidence may
          not bring success but it gives power to face any challenge.
        </p>
        <a
          class="btn btn-outline-light d-xs-none"
          href="{{url_for('main.story')}}"
          data-aos="fade-up"
          data-aos-delay="250"
          >Learn more</a
        >
      </div>
    </div>

    <!-- from series fateh series item -->
    {% for item in series%}
    <div class="carousel-item" style="max-height: 700px">
      <img
        class="d-block w-100"
        src="{{url_for('static', filename='img/'+item.image)}}"
        alt="Slide story image"
      />
      <div class="carousel-caption d-lg-block">
        <h1 class="display-4">{{item.name}}</h1>
        <p class="lead">{{item.slogan}}</p>
        <p class="text-small text-muted d-xl-block">{{item.description}}</p>
        <a
          class="btn btn-outline-light d-xs-none"
          href="{{ url_for('main.seriesUmbrellas', seriesid=item.id) }}"
          >Learn more</a
        >
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#topic-story" data-slide="prev">
    <img
      src="{{url_for('static', filename='img/arrows-left.svg')}}"
      width="24"
      height="24"
      alt="right"
    />
  </a>
  <a class="carousel-control-next" href="#topic-story" data-slide="next">
    <img
      src="{{url_for('static', filename='img/arrows-right.svg')}}"
      width="24"
      height="24"
      alt="left"
    />
  </a>
</div>
{% endblock %} {% block main %}
<!-- short description of the umbella website -->
<section>
  <div class="container my-5">
    <div class="text-white text-center">
      <div>
        <p class="h3 text-dark mb-4" data-aos="fade-down" data-aos-delay="50">
          A better excuse
        </p>
        <span style="color: #e34249">↓</span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <article>
          <h5 data-aos="fade-left" data-aos-delay="70">
            A sunny sky in the rain
          </h5>
          <p
            style="color: lightslategray"
            data-aos="fade-up"
            data-aos-delay="100"
          >
            Choose a right umbrella is as much important as you choose a best
            frind who gets your back. the umbella not only protect you fron
            servere weather but also allows you to show off.
          </p>
        </article>
      </div>
      <div class="col-md-6">
        <article>
          <h5 data-aos="fade-right" data-aos-delay="100">Why you need one?</h5>
          <p
            style="color: lightslategray"
            data-aos="fade-up"
            data-aos-delay="150"
          >
            An umbrella offers covering from sun or rain. No matter the weather,
            umbrellas have proved their usefulness and have a great meaning in
            society.
          </p>
        </article>
      </div>
    </div>
    <hr />
  </div>
</section>
<!-- marketing information -->
<section class="series-cards">
  <h3
    class="text-center"
    style="user-select: none; color: #e34249"
    id="Umbrella_anchor"
    data-aos="fade-up"
    data-aos-delay="100"
  >
    the Umbella total selection
  </h3>

  <!-- iterate each product -->
  <div class="card-columns">
    {% for umbrella in overall%}
    <article class="card m-3">
      <a href="{{ url_for('main.Umbrellas', umbrellaid=umbrella.id)}}">
        <img
          class="card-img"
          src="{{url_for('static', filename='img/'+umbrella.image)}}"
          alt="Card image"
        />
        <div
          class="card-img-overlay text-center p-auto d-flex flex-column justify-content-end"
        >
          <div class="card-body">
            <h4 class="card-title d-sm-block d-md-block">{{umbrella.name}}</h4>
            <h6
              class="card-subtitle mb-2 d-sm-none d-md-none d-lg-block d-xl-block"
            >
              {{umbrella.artist}}
            </h6>
            <p class="card-text d-sm-none d-md-none d-lg-none d-xl-block">
              {{umbrella.description}}
            </p>
          </div>
          <div class="add d-flex justify-content-around align-items-center">
            <div class="price d-sm-block d-md-block">
              <h6 class="card-text tag">AU${{umbrella.price}}</h6>
            </div>
            <div>
              <form action="{{ url_for('main.order') }}">
                <input
                  type="hidden"
                  id="umbrella_id"
                  name="umbrella_id"
                  value="{{ umbrella.id }}"
                />
                <input
                  class="btn btn-primary"
                  type="submit"
                  value="Add to cart"
                />
              </form>
            </div>
          </div>
        </div>
      </a>
    </article>
    {% endfor %}
  </div>
</section>

<!-- extra buttons links to other page -->
<div class="backToTop">
  <div class="mx-2"></div>
  <a
    href="{{ url_for('main.index', _anchor='Umbrella_anchor') }}"
    class="btn btn-light btn-sm"
    data-aos="fade-up"
    data-aos-delay="200"
    >view from top</a
  >
  <div class="mx-2"></div>
  <a
    href="{{ url_for('main.order') }}"
    class="btn btn-light btn-sm"
    data-aos="fade-up"
    data-aos-delay="300"
    >Go to cart</a
  >
</div>
{% endblock %}

umbella/templates/order.html
{% extends 'base.html' %}

{% block main %}
<style>
    .check_out_card:hover {
        box-shadow: 0px 5px 7px rgba(75,75,75,0.5);
        transition: all 0.5s;
        transition-timing-function: ease;
    }
</style>
<!-- display contents of user basket -->
<section>
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h1 data-aos="fade-up" data-aos-delay="100">Cart</h1>
        </div>
        <!-- each umbrella on seperate row -->
        {% for umbrella in order.umbrellas %}
        <div class="row m-3 ">
            <div class="col-sm-9 card p-0 check_out_card">
                <h5 class="card-header">{{umbrella.name}} <span class="font-weight-light">from {{umbrella.Series.name}}</span></h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4 col-sm-9 m-auto">
                            <a href="{{ url_for('main.Umbrellas', umbrellaid=umbrella.id)}}">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + umbrella.image))}}">
                            </a>
                        </div>
                        <div class="col-lg-7 col-sm-9 m-auto p-2" style="user-select: none; ">
                            <!-- Item Description -->
                            <p class="card-text text-left">{{umbrella.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <!-- right column has price and delete button -->
            <div class="col-sm-2 m-3 d-flex flex-column justify-content-center">
                <!-- delete item button -->
                <h5>{{ "$%.2f"|format(umbrella.price) }}</h5>
                <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                    <input type="hidden" id="id" name="id" value="{{umbrella.id}}">
                    <input type="submit" value="Delete item" class="btn btn-primary mb-3">
                </form>
            </div>
        </div>
        {% endfor %}

        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4" data-aos="fade-up" data-aos-delay="150">Total price: {{ "$%.2f"|format(totalprice) }}</h5>
            </div>

            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.index', _anchor='Umbrella_anchor') }}" class="btn btn-primary mr-4" data-aos="fade-up" data-aos-delay="100">Shop others</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary mr-4" data-aos="fade-up" data-aos-delay="200">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary" data-aos="fade-up" data-aos-delay="300">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}

umbella/templates/search.html
{% extends 'base.html' %}


{% block main %}

<!-- search result information --> 
<section class="series-cards">
    <h2 class="text-center" style="user-select: none;" id="Umbrella_anchor">Searching result...</h2>

    <div class="card-columns" >
        {% for umbrella in Umbrellas%}
        <article class="card my-3">
            <a href="{{ url_for('main.Umbrellas', umbrellaid=umbrella.id)}}">
                <img class="card-img" src="{{url_for('static', filename='img/'+umbrella.image)}}" alt="Card image">
                <div class="card-img-overlay text-center p-auto d-flex flex-column justify-content-end">
                    <div class="card-body">
                        <h4 class="card-title d-sm-block d-md-block">{{umbrella.name}}</h4>
                        <h6 class="card-subtitle mb-2 d-sm-none d-md-none d-lg-block d-xl-block">{{umbrella.artist}}
                        </h6>
                        <p class="card-text d-sm-none d-md-none d-lg-none d-xl-block">{{umbrella.description}}
                        </p>
                    </div>
                    <div class="add d-flex justify-content-around align-items-center">
                        <div class="price d-sm-block d-md-block">
                            <h6 class="card-text tag">A${{umbrella.price}}</h6>
                        </div>
                        <div>
                            <form action="{{ url_for('main.order') }}">
                                <input type="hidden" id="umbrella_id" name="umbrella_id" value="{{ umbrella.id }}">
                                <input class="btn btn-primary" type="submit" value="Add to cart">
                            </form>
                        </div>
                    </div>
                </div>
            </a>
        </article>
        {% endfor %}
    </div>
</section>    

{% endblock %}

umbella/templates/series.html
{% extends 'base.html' %}


{% block head %}
<!-- add a big banner to welcome user -->

<!-- Topic image -->
<div id="topic-story" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ul class="carousel-indicators">
        <li data-target="#topic-story" data-slide-to="0" class="active"></li>
    </ul>

    <div class="carousel-inner">
        <!-- the selected series item -->
        <div class="carousel-item active" style="max-height: 500px;">
            <img class="d-block w-100" src="{{url_for('static', filename='img/'+item.image)}}" alt="Slide story image">
            <div class="carousel-caption d-lg-block">
                <h1 class="display-4" data-aos="fade-left" data-aos-delay="200">{{item.name}}</h1>
                <p class="lead" data-aos="fade-right" data-aos-delay="300">{{item.slogan}}</p>
                <p class="text-small text-muted d-xl-block" data-aos="fade-up" data-aos-delay="400">{{item.description}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<!-- items information -->
<section class="series-cards">
    <h3 class="text-center mb-3" style="user-select: none; " data-aos="fade-up" data-aos-delay="200">the <span style="color: #e34249;" data-aos="fade-up" data-aos-delay="500">{{item.name}}</span> Style selection</h3>

    <div class="card-columns">
        
        {% for umbrella in umbrellas%}
        <article class="card my-3 mx-auto">
            <a href="{{ url_for('main.Umbrellas', umbrellaid=umbrella.id)}}">
                <img class="card-img" src="{{url_for('static', filename='img/'+umbrella.image)}}" alt="Card image">
                <div class="card-img-overlay text-center p-auto d-flex flex-column justify-content-end">
                    <div class="card-body">
                        <h4 class="card-title d-sm-block d-md-block">{{umbrella.name}}</h4>
                        <h6 class="card-subtitle mb-2 d-sm-none d-md-none d-lg-block d-xl-block">{{umbrella.artist}}
                        </h6>
                        <p class="card-text d-sm-none d-md-none d-lg-none d-xl-block">{{umbrella.description}}
                        </p>
                    </div>
                    <div class="add d-flex justify-content-around align-items-center">
                        <div class="price d-sm-block d-md-block">
                            <h6 class="card-text tag">A${{umbrella.price}}</h6>
                        </div>
                        <div>
                            <form action="{{ url_for('main.order') }}">
                                <input type="hidden" id="umbrella_id" name="umbrella_id" value="{{ umbrella.id }}">
                                <input class="btn btn-primary" type="submit" value="Add to cart">
                            </form>
                        </div>
                    </div>
                </div>
            </a>
        </article>
        {% endfor %}
    </div>
</section>

<div class="backToTop">
    <div class="mx-2"></div>
    <a href="{{ url_for('main.index', _anchor='Umbrella_anchor') }}" class="btn btn-light btn-sm" data-aos="fade-up"
        data-aos-delay="200">Shop others</a>
    <div class="mx-2"></div>
    <a href="{{ url_for('main.order') }}" class="btn btn-light btn-sm" data-aos="fade-up" data-aos-delay="300">Go to
        cart</a>
</div>
{% endblock %}